-- Generated by scripts/fetch-images.cjs (static curated)

-- ============ Universities ============
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/UniversityDamasEngineering.jpg/1280px-UniversityDamasEngineering.jpg' where slug = 'damascus';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Aleppo_University_1960s.jpg' where slug = 'aleppo';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/University_of_Latakia_building_and_perimeter_2002.jpg/1280px-University_of_Latakia_building_and_perimeter_2002.jpg' where slug = 'tishreen';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/3/35/Faculty_of_Medicine_in_Homs_University%2C_Syria.jpg' where slug = 'baath';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/6/67/%D9%85%D8%A8%D9%86%D9%89_%D8%AC%D8%A7%D9%85%D8%B9%D8%A9_%D8%A7%D9%84%D9%81%D8%B1%D8%A7%D8%AA.jpg' where slug = 'furat';
-- NO IMAGE for tartus
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/3/37/Hama_University_Logo.png' where slug = 'hama';
update public.universities set cover_url = 'https://smpumryithpdeipkdtap.supabase.co/storage/v1/object/public/university-images/sham-private-logo.png' where slug = 'sham-private';
update public.universities set cover_url = 'https://smpumryithpdeipkdtap.supabase.co/storage/v1/object/public/university-images/qalamoun-logo.png' where slug = 'qalamoun-private';
update public.universities set cover_url = 'https://smpumryithpdeipkdtap.supabase.co/storage/v1/object/public/university-images/qasioun-logo.png' where slug = 'qasioun-private';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Yarmouk_Private_University_Logo.png' where slug = 'yarmouk-private';
update public.universities set cover_url = 'https://smpumryithpdeipkdtap.supabase.co/storage/v1/object/public/university-images/iust-logo.png' where slug = 'iust';
update public.universities set cover_url = 'https://smpumryithpdeipkdtap.supabase.co/storage/v1/object/public/university-images/hawash-logo.png' where slug = 'hawash-private';
update public.universities set cover_url = 'https://smpumryithpdeipkdtap.supabase.co/storage/v1/object/public/university-images/ittihad-logo.gif' where slug = 'ittihad-private';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/a/a3/SVU-LOGO.jpg' where slug = 'svu';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/9/94/Aleppo-UniversitySquare-8Feb2025.jpg' where slug = 'free-aleppo';
update public.universities set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Gaziantep_University_logo.svg/1280px-Gaziantep_University_logo.svg.png' where slug = 'gaziantep-north';

-- ============ Majors ============
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/The_Doctor_Luke_Fildes_crop.jpg/1280px-The_Doctor_Luke_Fildes_crop.jpg' where name_ar = 'الطب البشري';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/20190202_GCC_%40_Moss_Dental_Clinic_-_46340656604.jpg/1280px-20190202_GCC_%40_Moss_Dental_Clinic_-_46340656604.jpg' where name_ar = 'طب الأسنان';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/PharmacistsMortar.svg/1280px-PharmacistsMortar.svg.png' where name_ar = 'الصيدلة';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Pexels-luis-gomes-546819.jpg/1280px-Pexels-luis-gomes-546819.jpg' where name_ar = 'الهندسة المعلوماتية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Virginia_Tech_-_data_center.jpg/1280px-Virginia_Tech_-_data_center.jpg' where name_ar = 'تقانة المعلومات';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Erdfunkstelle_Raisting_2.jpg/1280px-Erdfunkstelle_Raisting_2.jpg' where name_ar = 'تقانة الاتصالات';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Crane_and_new_Carrington_Bridge_-_geograph.org.uk_-_6778718.jpg' where name_ar = 'الهندسة المدنية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/View_of_Santa_Maria_del_Fiore_in_Florence.jpg/1280px-View_of_Santa_Maria_del_Fiore_in_Florence.jpg' where name_ar = 'الهندسة المعمارية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Umspannwerk-Pulverdingen_380kV-Trennschalter.jpg/1280px-Umspannwerk-Pulverdingen_380kV-Trennschalter.jpg' where name_ar = 'الهندسة الكهربائية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Mechanical_components.png' where name_ar = 'الهندسة الميكانيكية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Pumping_Oil_%285960977380%29.jpg/1280px-Pumping_Oil_%285960977380%29.jpg' where name_ar = 'الهندسة النفطية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/STM32F100C4T6B-HD.jpg/1280px-STM32F100C4T6B-HD.jpg' where name_ar = 'هندسة تقانة المعلومات';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Mechatronics.jpg' where name_ar = 'هندسة الميكاترونكس';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Math01.jpg/1280px-Math01.jpg' where name_ar = 'الرياضيات';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Quantum_Physics%3B_Paired_Atoms%3B_Untrapped_Atom_Pairs_%285941065432%29.jpg/1280px-Quantum_Physics%3B_Paired_Atoms%3B_Untrapped_Atom_Pairs_%285941065432%29.jpg' where name_ar = 'الفيزياء';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Reaction_Coordinate_Diagram.svg/1280px-Reaction_Coordinate_Diagram.svg.png' where name_ar = 'الكيمياء';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/DNA_simple_horizontal.svg/1280px-DNA_simple_horizontal.svg.png' where name_ar = 'علوم الحياة';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Conference_room_in_the_Berlaymont_building_2.JPG/1280px-Conference_room_in_the_Berlaymont_building_2.JPG' where name_ar = 'إدارة الأعمال';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Pacioli.jpg/1280px-Pacioli.jpg' where name_ar = 'المحاسبة';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Euro_M%C3%BCnzgeld_und_Portmonee_mit_gr%C3%BCnem_Pfeil_%28Geld%2C_Kleingeld%2C_M%C3%BCnzen%29.jpg/1280px-Euro_M%C3%BCnzgeld_und_Portmonee_mit_gr%C3%BCnem_Pfeil_%28Geld%2C_Kleingeld%2C_M%C3%BCnzen%29.jpg' where name_ar = 'الاقتصاد';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Justice_scale_silhouette%2C_medium.svg/1280px-Justice_scale_silhouette%2C_medium.svg.png' where name_ar = 'الحقوق';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Learning_Arabic_calligraphy.jpg' where name_ar = 'اللغة العربية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Library_books_1.jpg/1280px-Library_books_1.jpg' where name_ar = 'اللغة الإنجليزية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Carstian_Luyckx_-_Still_life_with_a_globe%2C_books%2C_shells_and_corals_resting_on_a_stone_ledge.jpg' where name_ar = 'التاريخ';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/CIA_World_Physical_Map_%282023%29.pdf/page1-1280px-CIA_World_Physical_Map_%282023%29.pdf.jpg' where name_ar = 'الجغرافيا';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/A_public_high_school_teacher_in_a_classroom_in_the_United_States_08.jpg/1280px-A_public_high_school_teacher_in_a_classroom_in_the_United_States_08.jpg' where name_ar = 'معلم صف';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Minaret_mosque_of_Paris.jpg/1280px-Minaret_mosque_of_Paris.jpg' where name_ar = 'الشريعة الإسلامية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/UN_General_Assembly_hall.jpg/1280px-UN_General_Assembly_hall.jpg' where name_ar = 'العلوم السياسية';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/UEFA_Euro_2020_-_Television_studio_01.jpg/1280px-UEFA_Euro_2020_-_Television_studio_01.jpg' where name_ar = 'الإعلام والاتصال';
update public.majors set cover_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Tractor_at_work_on_a_field_in_Idaho_%28cropped%29.jpg/1280px-Tractor_at_work_on_a_field_in_Idaho_%28cropped%29.jpg' where name_ar = 'الهندسة الزراعية';
